using Khronos;

namespace OpenGL;

public enum FragmentShaderConATI
{
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con0Ati = 35137,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con1Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con2Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con3Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con4Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con5Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con6Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con7Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con8Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con9Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con10Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con11Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con12Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con13Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con14Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con15Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con16Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con17Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con18Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con19Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con20Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con21Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con22Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con23Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con24Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con25Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con26Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con27Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con28Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con29Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con30Ati,
	[RequiredByFeature("GL_ATI_fragment_shader")]
	Con31Ati
}
