using Khronos;

namespace OpenGL;

public enum PathCoordType
{
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	ClosePathNv = 0,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	MoveToNv = 2,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeMoveToNv = 3,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	LineToNv = 4,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeLineToNv = 5,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	HorizontalLineToNv = 6,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeHorizontalLineToNv = 7,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	VerticalLineToNv = 8,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeVerticalLineToNv = 9,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	QuadraticCurveToNv = 10,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeQuadraticCurveToNv = 11,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	CubicCurveToNv = 12,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeCubicCurveToNv = 13,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	SmoothQuadraticCurveToNv = 14,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeSmoothQuadraticCurveToNv = 15,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	SmoothCubicCurveToNv = 16,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeSmoothCubicCurveToNv = 17,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	SmallCcwArcToNv = 18,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeSmallCcwArcToNv = 19,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	SmallCwArcToNv = 20,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeSmallCwArcToNv = 21,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	LargeCcwArcToNv = 22,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeLargeCcwArcToNv = 23,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	LargeCwArcToNv = 24,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeLargeCwArcToNv = 25,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	ConicCurveToNv = 26,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeConicCurveToNv = 27,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RoundedRectNv = 232,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeRoundedRectNv = 233,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RoundedRect2Nv = 234,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeRoundedRect2Nv = 235,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RoundedRect4Nv = 236,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeRoundedRect4Nv = 237,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RoundedRect8Nv = 238,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeRoundedRect8Nv = 239,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RestartPathNv = 240,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	DupFirstCubicCurveToNv = 242,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	DupLastCubicCurveToNv = 244,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RectNv = 246,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeRectNv = 247,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	CircularCcwArcToNv = 248,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	CircularCwArcToNv = 250,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	CircularTangentArcToNv = 252,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	ArcToNv = 254,
	[RequiredByFeature("GL_NV_path_rendering", Api = "gl|glcore|gles2")]
	RelativeArcToNv = 255
}
