namespace Vulkan;

public enum VkCoverageModulationModeNV
{
	VK_COVERAGE_MODULATION_MODE_NONE_NV,
	VK_COVERAGE_MODULATION_MODE_RGB_NV,
	VK_COVERAGE_MODULATION_MODE_ALPHA_NV,
	VK_COVERAGE_MODULATION_MODE_RGBA_NV
}
