namespace Vulkan;

public enum VkDebugReportObjectTypeEXT
{
	UnknownEXT = 0,
	InstanceEXT = 1,
	PhysicalDeviceEXT = 2,
	DeviceEXT = 3,
	QueueEXT = 4,
	SemaphoreEXT = 5,
	CommandBufferEXT = 6,
	FenceEXT = 7,
	DeviceMemoryEXT = 8,
	BufferEXT = 9,
	ImageEXT = 10,
	EventEXT = 11,
	QueryPoolEXT = 12,
	BufferViewEXT = 13,
	ImageViewEXT = 14,
	ShaderModuleEXT = 15,
	PipelineCacheEXT = 16,
	PipelineLayoutEXT = 17,
	RenderPassEXT = 18,
	PipelineEXT = 19,
	DescriptorSetLayoutEXT = 20,
	SamplerEXT = 21,
	DescriptorPoolEXT = 22,
	DescriptorSetEXT = 23,
	FramebufferEXT = 24,
	CommandPoolEXT = 25,
	SurfaceKHREXT = 26,
	SwapchainKHREXT = 27,
	DebugReportCallbackEXTEXT = 28,
	DisplayKHREXT = 29,
	DisplayModeKHREXT = 30,
	ObjectTableNVXEXT = 31,
	IndirectCommandsLayoutNVXEXT = 32,
	ValidationCacheEXTEXT = 33,
	DescriptorUpdateTemplateKHREXT = 1000085000,
	SamplerYcbcrConversionKHREXT = 1000156000
}
